//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSIgnupLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TblUserInfo
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        [Display(Name = "Enter Username")]
        public string UserName { get; set; }

        [Display(Name = "Enter Password")]
        [Required(ErrorMessage = "This field is required!")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is required!")]
        [DataType(DataType.Password)]
        [Compare("UserPassword",ErrorMessage ="Password and confirm password does not match, try again!")]
        [NotMapped]

        public string RePassword { get; set; }
    }
}
